site_name: My Porfolio Site

theme:
  name: material

nav:
  - About me: index.md
  - Value of savings: why-savings-matter.md
  - Integrate Clover payments plugin with Shopify: integrate-clover-payments-plugin-with-shopify-online-shop.md
  - Ecommerce tokenization overview: ecommerce-tokenization-overview.md
  - Error codes: ecommerce-error-codes.md
  - Compliance webhooks for Clover payments plugin: clover-payments-plugin-shopify-webhooks.md
  - Capture a charge: capture-a-charge-tutorial.md

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html

plugins:
  - search