site_name: My Porfolio Site

theme:
  name: material

  icon:
    logo: material/book-open-page-variant

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy

  palette:

  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode

  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - About Me: index.md

  - Portfolio:
      - Documentation Projects: portfolio/projects.md
      - Writing Samples: portfolio/writing-samples.md

  - AI Documentation:
      - Agentic AI: ai/agentic-ai.md
      - GenAI vs Agentic AI: ai/genai-vs-agentic.md
      - AI Documentation Strategy: ai/ai-documentation.md

  - Technical Writing:
      - Microsoft Style Guide: writing/microsoft-style-guide.md
      - Information Mapping: writing/information-mapping.md
      - Docs-as-Code: writing/docs-as-code.md

  - Resume:
      - Experience: resume/experience.md
      - Skills: resume/skills.md
      - Certifications: resume/certifications.md

  - Contact:
      - Contact Me: contact.md
  - Generative AI vs Agentic AI vs Agent Platforms: generative-aI-vs-agentic-aI-vs-agent-platforms.md
  - Value of Savings: why-savings-matter.md
  - Deploy Digitalai DevOps Platform on AWS: digitalai-devOps-platform.md
  - Capture a Charge (API): capture-a-charge-tutorial.md
  - Error Codes: ecommerce-error-codes.md
  - Ecommerce Tokenization: ecommerce-tokenization-overview.md
  - Integrate Clover Payments Plugin with Shopify: integrate-clover-payments-plugin-with-shopify-online-shop.md
  - Compliance Webhooks for Clover Payments Plugin: clover-payments-plugin-shopify-webhooks.md

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/arpitgupta007/

    - icon: fontawesome/brands/github
      link: https://arpitguptaa.github.io/my-docs-site/

    - icon: fontawesome/solid/envelope
      link: mailto: grtarpit2008@gmail.com

