name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Files
      - name: Run Vale
        uses: errata-ai/vale-action@reviewdog
        uses: actions/checkout@v4

      # Spell checking
      - name: Run CSpell
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*.md"

      # Broken link checking
      - name: Run Lychee Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose
            --no-progress
            --exclude "accounts.shopify.com"
            --exclude "abdm.gov.in"
            --exclude "financialeducation.rbi.org.in"
            --exclude "epfindia.gov.in"
            docs/**/*.md

      # Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Install MkDocs
      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      # Deploy documentation site
      - name: Deploy Website
        run: |
          mkdocs gh-deploy --force